### ISSUE TITLE
Brute force protection

### ISSUE THREAD

**Issue by codemonkey76** [codemonkey76/FightClubGrading#1]
Implement something like Sentry to guard against brute force login attempts.

**Comment by JaxTerra** [comment]
Sentry is awesome but it aint free. Laravel includes a loginthrottling trait we could use for this: https://laravel.com/docs/5.5/authentication#login-throttling

**Comment by codemonkey76** [comment]
Yeah all good, after some research, the LoginController uses the AuthenticatesUsers trait, which uses the ThrottlesLogins trait.
