### ISSUE TITLE
Approval system for new users

### ISSUE THREAD

**Issue by codemonkey76** [codemonkey76/FightClubGrading#3]
My account will be created by the seeder, and then any new accounts will need to be approved or rejected by existing users.

Notification icon in the navbar indicating there are unapproved users.

**Comment by JaxTerra** [comment]
This will require a Role table, then we make a couple of roles i.e. Admin, Super Admin and User. Then you are the Super Admin, assign the instructors the Admin roles and the student will be the user. Then we use a simple table listing all Users, with the pending at the top of the table or we can make a seperate table for pending users. 

I cant say im awesome at this but i know how its done and can easily use other projects of our to refer to.

**Comment by JaxTerra** [comment]
https://www.5balloons.info/user-role-based-authentication-and-access-control-in-laravel/

**Comment by codemonkey76** [comment]
I don't need roles, because Students won't be users of the system, well they won't need to login anyway. The only users with logins will be the instructors, and any instructor can approve any other user.

**Comment by JaxTerra** [comment]
Cool, sounds like you have a good understanding of what you want. Can you take this issue and ill help if needed?

**Comment by codemonkey76** [comment]
Yep
